- name: install packages
  hosts: local
  connection: local
  become: yes #using root credentails
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest 
    loop:
    - nginx
    - mysql
    - zip